name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
    
    - name: Build
      run: dotnet build C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
    - name: Test
      run: dotnet test C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
