name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 40
      minimum_runs:
        description: 'The minimum runs to keep for each workflow.'
        required: true
        default: 6

jobs:
  del_runs:
    runs-on: windows-latest
    steps:
      - name: Delete workflow runs
        uses: Ymlprojects/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
