name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build C:\Users\ranjitha.kirubakaran\source\repos\WebApplication2\WebApplication2.sln
    - name: Test
      run: dotnet test C:\Users\ranjitha.kirubakaran\source\repos\WebApplication2\WebApplication2.sln
