name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest
 

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0.403
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.403
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build WebApplication2.sln
      - name: Test
        run: dotnet test WebApplication2.sln
